Script started on 2021-08-27 09:57:36-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="188" LINES="13"]
]0;ben@Clover-VirtualBox: ~/cse113/lab0[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab0[00m$ gcc -g -Wall lab0[K[K[K[Khello.c -o hello
]0;ben@Clover-VirtualBox: ~/cse113/lab0[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab0[00m$ ./hello
Hello World!
]0;ben@Clover-VirtualBox: ~/cse113/lab0[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab0[00m$ exit
exit

Script done on 2021-08-27 09:59:56-06:00 [COMMAND_EXIT_CODE="0"]
